<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameGameGame.Core\GameGameGame.Core.csproj" />
    <ProjectReference Include="..\GameGameGame.Content\GameGameGame.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SadConsole.Host.MonoGame" Version="10.10.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>GameGameGame.Frontend.SadConsole</AssemblyName>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GameGameGame.Frontend.SadConsole.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\GameGameGame.Content\Beta\**\*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Content\Beta\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\assets\Candii.font">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>assets\Candii.font</TargetPath>
    </Content>
    <Content Include="..\..\assets\Candii.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>assets\Candii.png</TargetPath>
    </Content>
    <Content Include="..\..\assets\Candii16.font">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>assets\Candii16.font</TargetPath>
    </Content>
    <Content Include="..\..\assets\Candii16.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>assets\Candii16.png</TargetPath>
    </Content>
    <Content Include="..\..\assets\Candii.tileset.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>assets\Candii.tileset.json</TargetPath>
    </Content>
  </ItemGroup>

</Project>
