<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameGameGame.Core\GameGameGame.Core.csproj" />
    <ProjectReference Include="..\GameGameGame.Content\GameGameGame.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SadConsole.Host.MonoGame" Version="10.10.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>GameGameGame</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GameGameGame.SadConsole.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\GameGameGame.Content\Beta\**\*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Content\Beta\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

</Project>
