<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameGameGame.Content\GameGameGame.Content.csproj" />
    <ProjectReference Include="..\GameGameGame.Headless\GameGameGame.Headless.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

</Project>
