<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameGameGame.Core\GameGameGame.Core.csproj" />
    <ProjectReference Include="..\GameGameGame.Content\GameGameGame.Content.csproj" />
    <ProjectReference Include="..\GameGameGame.Headless\GameGameGame.Headless.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>GameGameGame</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\GameGameGame.Content\Beta\**\*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Content\Beta\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

</Project>
